# -*- coding: utf-8 -*-
"""Chatbot

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1znrMQA5PeH3DgTC0VsypPAOpHsCkbbpz
"""

import openai

def ai_journaling_assistant(entry, api_key):
    openai.api_key = api_key
    prompt = f"""
    You are a supportive journaling assistant. A student writes:

    \"{entry}\"

    Respond empathetically, offer validation, and include a wellness suggestion.
    """
    response = openai.ChatCompletion.create(
        model="gpt-3.5-turbo",
        messages=[{"role": "user", "content": prompt}],
        temperature=0.7
    )
    return response.choices[0].message.content